### PR TITLE
MoistAtmosphere density fix

### PR DESCRIPTION
**Pull request by Gordon-Dry**
As suggested by FreeThinker on Discord a couple of days ago ...

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
On hold.

I consider moving this whole PR to main Kerbalism.

**Comment by sswelm** [comment]
According to the resource file , MoistAtmosphere supposededly has a density of 0.000804. I notice that is very close to the density of Water which is 0.001. Saturated water vapor at STP has a true density of 4.85 g/m3 at 273 K , which translates into a density of 0.00000485  which is 165.77 times less than currently!!

**Comment by Gordon-Dry** [comment]
@sswelm thank you

**Comment by Gordon-Dry** [comment]
Because the stock Resource.cfg got other changes as well compared to this one, I suggest to apply this here whatsoever.

I will open a 2nd PR at stock Kerbalism.

**Comment by Gordon-Dry** [comment]
I close this in favor of
https://github.com/Kerbalism/Kerbalism/pull/456#issuecomment-509027255

**Pull request closed without merging**
